### ISSUE TITLE
[ 🏠 Home ] 홈 컴포넌트 구현

### ISSUE THREAD

**Issue by Happhee** [swu-graduation-exhibition/frontend#15]
## 🛠 Issue

홈 랜딩 페이지 구현 

## 📝 To-do

- [x] 컴포넌트 3단위로 분할
- [x] 이미지 위치 지정
- [x] 폰트 관련 설정
- [ ] 가로 스크롤 👉 react-query 적용
