### ISSUE TITLE
[ 🏠 Home ] 인터뷰 및 트랙소개 컴포넌트 구현 

### ISSUE THREAD

**Issue by Happhee** [swu-graduation-exhibition/frontend#19]
## 🛠 Issue

- 인터뷰 및 트랙소개 컴포넌트 구현 후 반응형 적용
- 홈 화면에 추가

## 📝 To-do

- [x] 인터뷰 컴포넌트 구현
- [x] 인터뷰 컴포넌트 반응형 적용
- [x] 가로 드래그 이벤트 구현
- [x] 트랙소개 컴포넌트 구현
- [x] 트랙소개 반응형 적용
