### ISSUE TITLE
[ 🎨 Designer ] 디자이너 상세페이지 작업

### ISSUE THREAD

**Issue by Happhee** [swu-graduation-exhibition/frontend#28]
## 🛠 Issue

- 디자이너 상세페이지 작업 및 반응형 구현

## 📝 To-do

- [x] 디자이너 상세페이지 작업
- [x] 클릭으로 페이지 이동
- [x] 반응형 폰트 크기 조절
- [x] 중첩라우팅 적용
